version: "3.9"

services:
  app:
    build: .
    container_name: refund-bot
    environment:
      # app'in .env değerlerini compose'a geçir
      SLACK_TOKEN: ${SLACK_TOKEN}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      FINANCE_CHANNEL: ${FINANCE_CHANNEL}
      APPROVER_USER_IDS: ${APPROVER_USER_IDS}
      # DB'yi container içindeki /data'ya yazalım
      DATABASE_URL: sqlite:////data/local.db
      TZ: Europe/Istanbul
    volumes:
      - db-data:/data
    ports:
      - "3000:3000"  # ngrok hâlâ localhost:3000'e tüneller
    depends_on:
      - fluent-bit
    # 🔁 stdout’u Fluent Bit’e gönder (docker logging driver: fluentd)
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: refund-bot

  fluent-bit:
    image: fluent/fluent-bit:2.2
    container_name: fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    ports:
      - "24224:24224"        # forward input (opsiyonel dışarı açma)
    depends_on:
      - elasticsearch
    networks:
      logging_net:
        ipv4_address: 172.30.0.10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      logging_net:
        ipv4_address: 172.30.0.11

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${KIBANA_ENCRYPTION_KEY}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - logging_net

networks:
  logging_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

volumes:
  db-data:
